name: millicent
description: Demonstrates how to use the just_audio plugin.
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  audio_session: ^0.1.14
  rxdart: ^0.27.2
  just_audio:
    path: ../../just_audio
  just_audio_background:
    path: ..
  url_launcher: ^6.3.0
  flutter_spinkit: ^5.2.1
  flutter_native_splash: ^2.4.1
  text_marquee: ^0.0.2
  transparent_image: ^2.0.0


# Uncomment when testing platform interface changes.
# dependency_overrides:
#   just_audio_platform_interface:
#     path: ../../just_audio_platform_interface
#   just_audio_web:
#     path: ../../just_audio_web


dev_dependencies:
  # TODO: uncomment these dependencies when they have nullsafe versions.
  # flutter_driver:
  #   sdk: flutter
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  # integration_test: ^1.0.1
  test: ^1.16.5
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  fonts:
    - family: Tiempos
      fonts:
        - asset: assets/fonts/TiemposHeadline.otf
    - family: Walfork
      fonts:
        - asset: assets/fonts/Walfork-Regular.ttf

  assets:
    - audio/
    - assets/images/millicent_sized_portrait_flutter.png
    - assets/images/millicent_icon.png
    - assets/images/default_cover.png
    - assets/images/rbb.png
    - assets/images/millicent_word.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/millicent_icon.png"
